version: '3'
services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
volumes:
  redis-data:
